name: 🐛 Bug Report
description: Report a bug or unexpected behavior in vibexp
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Thank you for taking the time to report a bug! Please provide as much detail as possible to help us reproduce and fix the issue.
  
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am running the latest version or have specified my version below
          required: true
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Frontend/UI
        - Backend API
        - Database
        - Authentication
        - MCP Integration
        - Agent System
        - Other
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide information about your environment
      placeholder: |
        - OS: [e.g. Windows 11, macOS 14, Ubuntu 22.04]
        - Browser (if applicable): [e.g. Chrome 120, Firefox 121]
        - vibexp version: [e.g. v1.2.3 or commit hash]
        - Backend API version (if known): [e.g. v0.5.0]
      render: markdown
    validations:
      required: true
  
  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs / Screenshots
      description: If applicable, add error logs, console output, or screenshots
      placeholder: Paste error messages or drag and drop screenshots here
      render: shell
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any additional information that might be helpful (network conditions, specific data, etc.)
    validations:
      required: false
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System is unusable
        - High - Major functionality broken
        - Medium - Feature partially working
        - Low - Minor issue or cosmetic
    validations:
      required: true

