name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (Please do not disclose sensitive details publicly)
title: "[Security]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Notice
        
        **IMPORTANT:** If you believe you've found a critical security vulnerability, please follow our [responsible disclosure process](../SECURITY.md) instead of creating a public issue.
        
        For non-critical security concerns or questions, you may use this template.
        
  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Acknowledgment
      description: Please confirm you understand the security guidelines
      options:
        - label: I have read the security guidelines and this is not a critical vulnerability
          required: true
        - label: I have searched existing issues to avoid duplicates
          required: true
  
  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear and concise description of the security concern
      placeholder: Describe the security issue or concern
    validations:
      required: true
  
  - type: dropdown
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      multiple: true
      options:
        - Latest release
        - Specific version (specify in additional context)
        - Development/main branch
        - Unknown
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps To Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Step one
        2. Step two
        3. ...
    validations:
      required: true
  
  - type: dropdown
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      options:
        - Low - Minimal impact
        - Medium - Moderate impact
        - High - Significant impact
        - Critical - Severe impact
        - Unknown
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution (Optional)
      description: If you have suggestions for fixing this issue, please share them
      placeholder: Describe potential solutions or mitigations
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or logs about the security concern
      placeholder: Any additional information that might be helpful
    validations:
      required: false

